[package]
name = "pickture-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
fast_image_resize.workspace = true
jpeg-decoder.workspace = true
kamadak-exif.workspace = true
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
directories.workspace = true
anyhow.workspace = true
